### ISSUE TITLE
Device removed and the status is online and still enrolled

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#106]
### Expected behaviour

Unenroll the agent on the device.

### Actual behaviour

The agent status is online and still enrolled.

### Environment Details

- Android Version: 6.0
- Device: LG-K220
- App Version: 1.0.104

### Steps to reproduce the behaviour

* Remove the device in the devices list of the Admin Dashboard.
* Open the Agent on Android.

### Screenshots

![imagen](https://user-images.githubusercontent.com/663460/28566694-39f8af8e-7130-11e7-9184-452ee602ea73.png)

**Comment by btry** [comment]
If we unenroll an agent, a MQTT message is sent to the agent to request unenrollment. This message is retained so when the device goes online, it must be notified. (no QoS though, not sure it is needed).

So when the device is warned about this action, it must ake it into account to display the up to date informations.

The agent must complete unenrollment and send a MQTT message to ACK the request.
