### ISSUE TITLE
Snackbars for status and error patterns

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#108]
Hi, @rafaelje 

Please use snackbars in these cases:

- [x] Show snackbars for the status of the enrollment wizard.
- [x] Show snackbars for the status of the M2M communications.

References:
https://material.io/guidelines/components/snackbars-toasts.html
https://material.io/guidelines/patterns/errors.html#errors-incompatible-state-errors

**Comment by rafaelje** [comment]
To complete this issue with M2M communications is needed clean, remove and manage all broadcast message to prevent memory leak
