### ISSUE TITLE
Crash report / feedback

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#115]
Hi, @Rafaelje.

How we can receive this Feedback from crash of the android app?

---

![imagen](https://user-images.githubusercontent.com/663460/28696914-d7fcb6da-7338-11e7-8d44-1c005f3b2864.png)

**Comment by ajsb85** [comment]
Custom Activity On Crash library:
https://github.com/Ereza/CustomActivityOnCrash

**Comment by ajsb85** [comment]
Sherlock reports any crash that occurres in your application
https://github.com/ajitsing/Sherlock

**Comment by ajsb85** [comment]
Android crash reporting libraries
http://www.appbrain.com/stats/libraries/tag/crash-reporting/android-crash-reporting-libraries

**Comment by ajsb85** [comment]
Application Crash Reports for Android 
https://github.com/ACRA/acra

**Comment by ajsb85** [comment]
Hi, @rafaelje 

After the enrollement sucess, you can get the initial settings with the keys for the ACRA

```JSON
  "android_bugcollecctor_url": "",
  "android_bugcollector_login": "",
  "android_bugcollector_passwd": "",
```

Here is the documentation:

https://github.com/flyve-mdm/flyve-mdm-glpi-plugin/wiki/Enrollment_process#get-agents-initial-settings-only-if-enrollment-succeeded

**Comment by ajsb85** [comment]
Hi, @rafaelje 

So, we will use @bugsnag and @thestralbot here also.

@btry could you add the link `https://hooks.thestralbot.com/-1001061475099/`
For the key `android_bugcollecctor_url`

Merci !

**Comment by btry** [comment]
done
