### ISSUE TITLE
Create user information screen

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-android-agent#117]
Create screen to edit the user agent information

**Comment by ajsb85** [comment]
Hi, @rafaelje  

Add more fields and features to this screen on the iOS MDM Agent to accomplish the entire features of the GLPI interface, try to create the module to reuse later for the dashboard:

https://dev.flyve.org/glpi/front/preference.php

![imagen](https://user-images.githubusercontent.com/663460/28862576-c9f7c954-7765-11e7-99ee-b386b7ed8769.png)
