### ISSUE TITLE
Create project page

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-android-agent#126]
Create gh-pages as requested in this issue: flyve-mdm/flyve-mdm.github.io#13

**Comment by ajsb85** [comment]
Hi, @rafaelje 
The project site is here at the moment: http://flyve.org/flyve-mdm-android-agent/
I will close this issue.
Good job @Gianfranco97 
Best regards

**Comment by ajsb85** [comment]
btw, @rafaelje don't triage to the MDM Agent project, this issue is related to the Web site project.
