### ISSUE TITLE
New requirement in enrollment

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-android-agent#140]
the backend will require the agent provides its MDM type at enrollment time.

For Android: a new key "type" must contain "android".

Other types expected in a near future:
- apple
- samsung
- blackberry
- google
- windows

As this is dependent on the agent project, I think it is sufficient to hard code id. This may change when we'll implement samsung MDM for example.

**Comment by ajsb85** [comment]
@btry And Windows (Windows 10 Mobile) 

Microsoft Intune, Mobile Device Management for Office 365, and Microsoft System Center Configuration Manager
