### ISSUE TITLE
Indentify MDM platform

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#144]
Hi, @rafaelje 

You need to send a new key in the payload to identify the MDM platform.
We will use Android (AOSP and others), BlackBerry and Samsung for the Android based operating system.

It's mandatory.

Here below is the documentation from the Wiki of the GLPI Plugin.

The new key is `type`

Thanks.

### Instanciation of the agent
After a session token is acquired, the agent must create itself in the backend. It must send its serial number or its UUID. Sending both is recommended to avoid inventory problems.

```
POST http://api.domain.com/PluginFlyvemdmAgent?session_token=83af7e620c83a50a18d3eac2f6ed05a3ca0bea62
Content-Type: application/json
```

Payload 

```json
{"input":
  {
    "_email": "emailaddress@domain.com",
    "_invitation_token": "lkhjfkgsdf546634s",
    "_serial": "0123456ATDJ-045",
    "_uuid": "49D53434-0200-9D08-9000-01DEA9028055",
    "csr": "",
    "firstname": "my first name",
    "lastname": "my lastname",
    "version": "0.99.0",
    "type": "android"
  }
}
```

* _email: email address of the invited user
* _invitation_token: invitation token foundin  the invitation message
* _serial: serial number of the device (serial or uuid required, both is better)
* _uuid: UUID of the device (serial or uuid required, both is better)
* csr: certificate signing request (not implemented yet)
* firstname: first name of the user (optional)
* lastname: lastname of the user (optional)
* version: version of the MDM agent
* type: type of MDM used (must be one of the MDM types supported by the backend)  

Note: csr is a certificate signing request : not fully implemented for now.

**Comment by btry** [comment]
duplicates #140
