### ISSUE TITLE
 Android Release Workflow

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#146]
Hi, @rafaelje 

Here is the workflow proposed for the release:

- [ ] Create an issue for the feature or hotfix
- [ ] Commit and create the PR
- [ ] Run the tests and Quality Control with the PR
- [ ] Accept PR (Close the issue)
- [ ] Run conventional-recommended-bump (and store the version in the manifest)
- [ ] Build the apk
- [ ] Upload to Google Play as beta
- [ ] Fastlane notify the Telegram group
- [ ] Schedule a day (in the milestone) to merge master from develop
- [ ] Merge master from develop
- [ ] Run conventional-recommended-bump (and store the version in the manifest)
- [ ] Git add and git commit the manifest (with a proper commit message)
- [ ] Run standard-version (create changelod with the proper commit and the tag)
- [ ] Run GitHub releaser
- [ ] commit and push CHANGELOG.md to gh-pages
- [ ] Upload the APK to GitHub 
- [ ] Upload to Google Play as release
- [ ] Upload to F-Droid

Best regards.

**Comment by rafaelje** [comment]
I had problems sending CHANGELOG.md to gh-pages, @ajsb85 did you know any way to push just one file to another branch?

**Comment by ajsb85** [comment]
Hi, @rafaelje

`git checkout gh-pages`

But the `CHANGELOG.md` need this header:

```YAML
---
layout: modal
title: changelog
---
```
