### ISSUE TITLE
Handle App Link 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#157]
Hi, @rafaelje 

Could you add also the deeplink as http procotol in the App Manifest?

Correlative:
https://github.com/flyve-mdm/flyve-mdm-deeplink/issues/1

**Comment by ajsb85** [comment]
@ajsb85 Reference:
https://developer.android.com/training/app-links/deep-linking.html

**Comment by rafaelje** [comment]
This issue is ready and merge on develop https://github.com/flyve-mdm/flyve-mdm-android-agent/blob/develop/app/src/main/AndroidManifest.xml
