### ISSUE TITLE
MDM type missing

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/flyve-mdm-android-agent#161]
Hi, @rafaelje 

### Expected behaviour
Enroll Android 7.0 Phone
### Actual behaviour
Error on application after initial data for enrollment
### Environment Details

Environment Details

HTTP server version: Apache/2.4.18 (Ubuntu) Server
GLPi version: 9.2
Flyve MDM version: 2.0.0-dev
FusionInventory version: 9.2+1.0
Mosquitto version: 1.4.8 (build date Mon, 26 Jun 2017 09:31:02 +0100)
Mosquitto's auth plugin version: (0.0.7-2build1)
FlyveMDM Android App: 3.0.0

### Steps to reproduce the behaviour

1.Create invitation
2.Hit the enroll link
3.Authentication is succesful (verified through glpi _log event.log.)
4.Insert user data hit the check mark
5.MDM type missing on the phone, nothing on any log of the glpi server. No enrollment.

Also what is the Administrative Number field??
### Screenshots, backtraces or logs
![screenshot_20171004-085849](https://user-images.githubusercontent.com/9021998/31161983-5a26e39e-a8e3-11e7-9417-7bfd7f2fbaab.png)

Refer: https://github.com/flyve-mdm/flyve-mdm-glpi-plugin/issues/130

**Comment by ajsb85** [comment]
Hi, @rafaelje 
Could you fix this issue with Domingo and release the beta, to continue testing the new features of the backend.
Thank you.

**Comment by grego1981** [comment]
Any news on the app? Can we test now?

Thank you!!

**Comment by ajsb85** [comment]
@rafaelje, try to resolve this issue in particular as soon as possible.
