### ISSUE TITLE
Wrong link for Web Console

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/flyve-mdm-android-agent#170]
### Expected behaviour
Go to the correct Administration Web Console

### Actual behaviour
The link goes to http://demo.flyve.org

### Environment Details

- Android Version :  6
- Device : Blu
- App Version : 1

### Steps to reproduce the behaviour
Run the app for fist time ever (without registration), in the second screen where you ask the user to get a free trial click on "Administration Web Console"

**Comment by rafaelje** [comment]
@ajsb85 do you think that this "http://flyve.org/" is the link of "Administration Web Console"

**Comment by ajsb85** [comment]
We need a env var in the Circle CI, to use dev.flyve.org (beta) or demo.flyve.org (release)

**Comment by rafaelje** [comment]
Ok I'll create a new one `ADMIN_WEB_CONSOLE` env var on CircleCI
