### ISSUE TITLE
Disable Usb File Transfer Protocols

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-android-agent#187]
Disable USB file transfer protocols:
Require /system/data or root

- adb
- mtp 
- ptp

Example:

```
# disable usb
setprop persist.sys.usb.config none

#enable usb
setprop persist.sys.usb.config mtp,ptp,adb
```

**Comment by ajsb85** [comment]
@rafaelje So, the options are one or multiples of these: mtp, ptp, adb /cc @btry0

**Comment by rafaelje** [comment]
Yes we can use multiples options

**Comment by btry** [comment]
HI 

Then I'll "explode" the policy into 3: one for each setting
