### ISSUE TITLE
Android screenOrientation management

### ISSUE THREAD

**Issue by dlarget** [flyve-mdm/flyve-mdm-android-agent#2]
### Environment Details

- Android Version : 6.0.1
- Device : Nexus 5
- App Version : 0.99.41

### Steps to reproduce the behaviour

when device is in landscape app bug

**Comment by ajsb85** [comment]
We are rewriting the app.

**Comment by ajsb85** [comment]
Closed in 3bcb210b1451a8015a17381d0fb7ce8cef76f379
