### ISSUE TITLE
Random black screen

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#24]
![image](https://cloud.githubusercontent.com/assets/663460/24447999/137b57e0-1473-11e7-9efd-40c019ad52e5.png)

![image](https://cloud.githubusercontent.com/assets/663460/24448006/1732af3c-1473-11e7-9124-c1e44fdb7250.png)

**Comment by TICgal** [comment]
Maybe it is only a coincidence, but I've noticed it happens a lot when using the Camera App.

**Comment by ajsb85** [comment]
We are re-writing the app.
