### ISSUE TITLE
Using MQTT over SSL

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#33]
We fully disabled clear MQTT on port 1883.
Currently, the agent contains a .pem to validate the certification chain.
We must find a way to no longer need  this

TCP/IP port 1883 is reserved with IANA for use with MQTT. 
TCP/IP port 8883 is also registered, for using MQTT over SSL.

https://github.com/flyve-mdm/flyve-mdm-android/blob/master/app/src/main/assets/flyve.org.ca.crt

[flyve.org.pem.zip](https://github.com/flyve-mdm/flyve-mdm-android/files/971070/flyve.org.pem.crt.zip)

**Comment by btry** [comment]
- SSL connection is implemented
- needs to finish work on mutual authentication between server and client with SSL certificates.
