### ISSUE TITLE
Add IntentService to improved the performance

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-android-agent#43]
The app is using Services but we can improved the performance with IntentService

**Comment by ajsb85** [comment]
Creating a Background Service
https://developer.android.com/training/run-background-service/create-service.html

IntentService
https://developer.android.com/reference/android/app/IntentService.html

**Comment by ajsb85** [comment]
Service vs IntentService
http://stackoverflow.com/questions/7771323/what-is-the-difference-between-an-intentservice-and-a-service
