### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#48]
## Ping query

Sub topic ```Command/Ping```

```
 {
    "query" : "Ping"
}
```

Expected answer

Sub topic ```Status/Ping```
``` ! ```

**Comment by rafaelje** [comment]
This issue is ready on branch feature-start why is not close?

**Comment by ajsb85** [comment]
@rafaelje The branch is merged into master?

**Comment by rafaelje** [comment]
@ajsb85 for me this issue need to be close
