### ISSUE TITLE
Version manifest

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#57]
## FlyveMDM version manifest

This subtopic contains metadata about Flyve MDM published to each device. This is the current version of the backend.

Sub topic ```/FlyvemdmManifest/Status/Version```

```
{
    "version":"0.6.0"
}
```

**Comment by btry** [comment]
This information is provided to agents and updates itself when the plgin is updated. The agent uses this information to determine its compatibility with the backend.
