### ISSUE TITLE
Turn off GPS 

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-android-agent#69]
Hi, @ajsb85

Turn off GPS need system app for any api Android under 23 and user app for API 23 or above, review if the app is installed on /system or /data to manage GPS settings

* Check this: 
https://developer.android.com/reference/android/Manifest.permission.html#WRITE_SETTINGS

* “Write settings” permission not granted marshmallow android
https://stackoverflow.com/questions/39224303/write-settings-permission-not-granted-marshmallow-android/39224511#39224511

* Can't get WRITE_SETTINGS permission
https://stackoverflow.com/questions/32083410/cant-get-write-settings-permission

**Comment by ajsb85** [comment]
Hi, @rafaelje 

For the presentation the next 28th of Nov in Portugal, we need to integrate this feature in a system app. 

We will put the MDM Agent into the /system/app folder in the AOSP.

Could you root an Android device and try these system permissions?

Thanks.

**Comment by rafaelje** [comment]
This are some instruction to install this apk on system/app with adb in a root device:

```
adb shell
su
mount -o rw,remount /system
```

The easy way is move the apk to the device and If the apk is on external sdcard this is an example to move to the system folder:

for Android 4.3 or newest
```
mv /storage/sdcard1/file.apk /system/priv-app
```

For older Android devices
```
mv /storage/sdcard1/file.apk /system/app
```

You need change the permission of this file to execute
```
chmod 644 file.apk
```

Then you need exit and reboot the device to take changes
```
# maybe you need more than one exit
exit 
adb reboot
```

**Comment by ajsb85** [comment]
Hi, @rafaelje I will test the app with several devices and Android versions as system app.

Could you share with me the apk file?

Thank you.

**Comment by rafaelje** [comment]
@ajsb85 yes off course I'll send you

**Comment by ajsb85** [comment]
A new command to push the apk

`adb push flyvemdm.apk /storage/self/primary/file.apk`

`adb push flyvemdm.apk /storage/sdcard1/file.apk`
