### ISSUE TITLE
It reboots after close

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#71]
![imagen](https://user-images.githubusercontent.com/663460/27980358-26ab4faa-637e-11e7-9ec5-04fe83a51bdb.png)

![imagen](https://user-images.githubusercontent.com/663460/27980360-2cd0dc9c-637e-11e7-805d-6c067657a900.png)

**Comment by ajsb85** [comment]
Starting Background Services
https://guides.codepath.com/android/Starting-Background-Services

**Comment by rafaelje** [comment]
This is a regular behavior on service, the implementation is correct, when you start the main app both (service and app) are in the same thread when you close the app, create a new thread for service, I find information, check other apps and have the same behaviors like whatsapp, facebook and others apps with background process.

**Comment by ajsb85** [comment]
@rafaelje Perfect.
