### ISSUE TITLE
Screen after install - Mobile Phone Portrait 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#73]
* When the user open the application after install it. 

![artboard 14](https://user-images.githubusercontent.com/663460/28067644-54694b6a-6642-11e7-99cb-f528dfe334f4.png)

**Comment by rafaelje** [comment]
We need a button or something here to open the QR scanner

**Comment by ajsb85** [comment]
@rafaelje No. The internal QR scanner is buggy. And the user need to wait an invitation to enroll the device

**Comment by ajsb85** [comment]
@rafaelje May we can put a help button to know the enrollment procedure.

**Comment by ajsb85** [comment]
New logotype

![artboard 14](https://user-images.githubusercontent.com/663460/28142876-2f4e3f9e-6763-11e7-8e68-78dfa9852201.png)
