### ISSUE TITLE
Screen after the enroll is completed - Mobile Phone Portrait

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#78]
* Show this screen a couple of seconds before the normal screen.

![artboard 20](https://user-images.githubusercontent.com/663460/28070288-9fec783c-664c-11e7-991a-b33e05d2c750.png)

**Comment by ajsb85** [comment]
New logotype

![artboard 15](https://user-images.githubusercontent.com/663460/28142998-afd6b24a-6763-11e7-955c-9e51d33f95f0.png)

**Comment by rafaelje** [comment]
IMO This is an unnecessary screen when the user enrolls successfully want to go directly to the main screen

**Comment by ajsb85** [comment]
Ok.
