### ISSUE TITLE
After successful enrollment I can go back to the previous activity

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-android-agent#97]
### Expected behaviour
After successful enrollment close the enrollment process

### Actual behaviour
After successful enrollment I can go back to the previous activity

**Comment by ajsb85** [comment]
Closed in 3bcb210b1451a8015a17381d0fb7ce8cef76f379

**Comment by ajsb85** [comment]
Closed in 3bcb210b1451a8015a17381d0fb7ce8cef76f379
