### ISSUE TITLE
Navigation history

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-agent#99]
Remove the history to go back after the enrollment success

**Comment by rafaelje** [comment]
@ajsb85 Please can you be more explicit on this issue when you maybe this issue was solved here https://github.com/flyve-mdm/flyve-mdm-android-agent/issues/97

**Comment by ajsb85** [comment]
Still appear this first windows after enroll when I go back.

![imagen](https://user-images.githubusercontent.com/663460/28490638-3e44cfa8-6edf-11e7-9bc5-8f5f7b7ab589.png)

**Comment by rafaelje** [comment]
I can't reproduce this issue on this two sceneries:

1.- open the app first-time, user enroll and go back
2.- open the app before enrollment and go back

This is first case
![navigation small480x320](https://user-images.githubusercontent.com/4085091/28494595-d54ab374-6f00-11e7-89ad-58711d3cea92.gif)

**Comment by ajsb85** [comment]
1. Open the app without deeplinks
2. keep open
3. and after that open the deeplink
4. and then enroll the device
5. and go back
